# Generated by Django 2.2.5 on 2019-10-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_editor_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_image',
            field=models.ImageField(default='articles/default.jpg', upload_to='articles/'),
        ),
    ]
